apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac-poc
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: rhcl-rbac-poc
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HugoPfeffer/sema-mt-rhcl-poc.git
    targetRevision: main
    path: src/rbac-poc
    helm:
      valuesObject:
        host: rbac-api.rhcl.sandbox3759.opentlc.com
  destination:
    server: https://kubernetes.default.svc
    namespace: rbac-poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
