apiVersion: v1
kind: Service
metadata:
  name: {{ include "rbac-poc.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rbac-poc.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "rbac-poc.name" . }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
